Added Jenkins worker and Ruby builder for vocab

diff --git a/docker_containers/jenkins-container/1/test/run b/docker_containers/jenkins-container/1/test/run
--- a/docker_containers/jenkins-container/1/test/run
+++ b/docker_containers/jenkins-container/1/test/run
@@ -11,6 +11,8 @@ shopt -s nullglob
 
 IMAGE_NAME=${IMAGE_NAME-openshift/jenkins-1-centos7-candidate}
 
+FAILURE=true
+
 CIDFILE_DIR=$(mktemp --suffix=jenkins_test_cidfiles -d)
 VOLUME=`mktemp -d`
 chmod a+rwx $VOLUME
@@ -22,10 +24,8 @@ function cleanup() {
     echo "Stopping and removing container $CONTAINER..."
     docker stop $CONTAINER
     exit_status=$(docker inspect -f '{{.State.ExitCode}}' $CONTAINER)
-    echo "Dumping logs for $CONTAINER"
-    # Dump the logs always (jenkins returns 143 when killed), so we can
-    # identify the failures in Jenkins
-    [[ "${exit_status}" != "143" ]] && docker logs $CONTAINER
+    [[ "${FAILURE}" == "true" ]] && echo "Dumping logs for $CONTAINER"
+    [[ "${FAILURE}" == "true" ]] && docker logs $CONTAINER
     docker rm $CONTAINER
     rm $cidfile
     echo "Done."
@@ -49,7 +49,7 @@ function get_container_ip() {
 test_connection() {
   set +e
   echo "Testing HTTP connection..."
-  local max_attempts=10
+  local max_attempts=20
   local sleep_time=6
   local attempt=1
   local result=1
@@ -103,10 +103,21 @@ function test_get_job() {
 
 function run_tests() {
   local name=$1 ; shift
-  CONTAINER_ARGS="-u 10000:0"
   create_container $name $VOLUME
   CONTAINER_IP=$(get_container_ip $name)
   test_connection $name
+
+  # Make sure no plugins failed to load
+  set +e
+  CONTAINER=$(cat $cidfile)
+  docker logs $CONTAINER |& grep "Failed Loading plugin"
+  rc=$?
+  set -e
+  if [ $rc -eq 0 ]; then
+    echo "Failed loading plugins"
+    return 1
+  fi
+
   test_create_job admin password testJob
   test_get_job admin password testJob
   set +e
@@ -137,7 +148,6 @@ function run_tests() {
   set -e
   # Stop the container so next tests can run
   docker stop $(get_cid $name)
-  echo "  Success!"
 }
 
 function run_s2i_tests() {
@@ -181,9 +191,21 @@ function run_s2i_tests() {
 # Tests.
 
 # Normal tests
+echo "Normal test: 64 bit"
+CONTAINER_ARGS="-u 10000:0 -e OPENSHIFT_JENKINS_JVM_ARCH=x86_64"
+run_tests jenkins_test
+cleanup
+sleep 5
+echo "Normal test: 32 bit"
+CIDFILE_DIR=$(mktemp --suffix=jenkins_test_cidfiles -d)
+VOLUME=`mktemp -d`
+chmod a+rwx $VOLUME
+CONTAINER_ARGS="-u 10000:0 -e OPENSHIFT_JENKINS_JVM_ARCH=i386 "
 run_tests jenkins_test
 
 # S2I tests
 run_s2i_tests
+
+FAILURE=false
 
 echo "SUCCESS!"
diff --git a/docker_containers/jenkins-container/2/test/run b/docker_containers/jenkins-container/2/test/run
--- a/docker_containers/jenkins-container/2/test/run
+++ b/docker_containers/jenkins-container/2/test/run
@@ -9,7 +9,9 @@
 set -eo nounset
 shopt -s nullglob
 
-IMAGE_NAME=${IMAGE_NAME-openshift/jenkins-1-centos7-candidate}
+IMAGE_NAME=${IMAGE_NAME-openshift/jenkins-2-centos7-candidate}
+
+FAILURE=true
 
 CIDFILE_DIR=$(mktemp --suffix=jenkins_test_cidfiles -d)
 VOLUME=`mktemp -d`
@@ -22,10 +24,8 @@ function cleanup() {
     echo "Stopping and removing container $CONTAINER..."
     docker stop $CONTAINER
     exit_status=$(docker inspect -f '{{.State.ExitCode}}' $CONTAINER)
-    echo "Dumping logs for $CONTAINER"
-    # Dump the logs always (jenkins returns 143 when killed), so we can
-    # identify the failures in Jenkins
-    [[ "${exit_status}" != "143" ]] && docker logs $CONTAINER
+    [[ "${FAILURE}" == "true" ]] && echo "Dumping logs for $CONTAINER"
+    [[ "${FAILURE}" == "true" ]] && docker logs $CONTAINER
     docker rm $CONTAINER
     rm $cidfile
     echo "Done."
@@ -49,7 +49,7 @@ function get_container_ip() {
 test_connection() {
   set +e
   echo "Testing HTTP connection..."
-  local max_attempts=10
+  local max_attempts=20
   local sleep_time=6
   local attempt=1
   local result=1
@@ -70,7 +70,7 @@ test_connection() {
   return $result
 }
 
-function create_container() {
+function run_image() {
   local name=$1 ; shift
   local volume=$1; shift
   local cargs=${CONTAINER_ARGS:-}
@@ -91,36 +91,65 @@ function delete_container() {
 # $2 - password
 # $3 - job name
 function test_create_job() {
-  curl --fail --user $1:$2 -X POST -H "Content-Type: application/xml" -H "Expect: " --data-binary '@test/testjob.xml' http://${CONTAINER_IP}:8080/createItem\?name=$3
+  curl -s --fail --user $1:$2 -X POST -H "Content-Type: application/xml" -H "Expect: " --data-binary '@test/testjob.xml' http://${CONTAINER_IP}:8080/createItem\?name=$3
 }
 
 # $1 - username
 # $2 - password
 # $3 - job name
 function test_get_job() {
-  curl --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/job/$3
+  curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/job/$3
+}
+
+function test_non_pipeline_dependencies_pulled() {
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/ace-editor/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/branch-api/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/credentials/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/durable-task/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/cloudbees-folder/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/git-server/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/git-client/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/git/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/handlebars/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/momentjs/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/plain-credentials/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/scm-api/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/script-security/thirdPartyLicenses
+    curl -s --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/pluginManager/plugin/structs/thirdPartyLicenses
 }
 
 function run_tests() {
   local name=$1 ; shift
-  CONTAINER_ARGS="-u 10000:0"
-  create_container $name $VOLUME
+  run_image $name $VOLUME
   CONTAINER_IP=$(get_container_ip $name)
   test_connection $name
+
+  # Make sure no plugins failed to load
+  set +e
+  CONTAINER=$(cat $cidfile)
+  docker logs $CONTAINER |& grep "Failed Loading plugin"
+  rc=$?
+  set -e
+  if [ $rc -eq 0 ]; then
+    echo "Failed loading plugins"
+    return 1
+  fi
+
   test_create_job admin password testJob
   test_get_job admin password testJob
   set +e
   test_create_job admin badpassword failJob
-  if [ $? -eq 0 ]; then
+  rc=$?
+  set -e
+  if [ $rc -eq 0 ]; then
     echo "Fail: was able to create job with bad password"
     return 1
   fi
-  set -e
 
   delete_container
 
   # start a new container with the old volume so we can try to change the password
-  CONTAINER_ARGS="-u 10000:0 -e JENKINS_PASSWORD=newpassword" create_container $name $VOLUME
+  CONTAINER_ARGS="-u 10000:0 -e JENKINS_PASSWORD=newpassword" run_image $name $VOLUME
   CONTAINER_IP=$(get_container_ip $name)
 
   # need this to wait for the container to start up
@@ -130,14 +159,15 @@ function run_tests() {
   set +e
   # old password should not
   test_get_job admin password testJob
-  if [ $? -eq 0 ]; then
+  rc=$?
+  set -e
+  if [ $rc -eq 0 ]; then
     echo "Fail: was able to get job with bad password"
     return 1
   fi
-  set -e
+  test_non_pipeline_dependencies_pulled admin newpassword
   # Stop the container so next tests can run
   docker stop $(get_cid $name)
-  echo "  Success!"
 }
 
 function run_s2i_tests() {
@@ -146,15 +176,15 @@ function run_s2i_tests() {
     return
   fi
   output_image="openshift/s2i-test-jenkins"
-  s2i build --context-dir="1/test/s2i" --loglevel=3 --pull-policy=never \
+  s2i build --context-dir="2/test/s2i" --loglevel=3 --pull-policy=never \
     file://$(pwd)/.. $IMAGE_NAME $output_image
   s2i_volume=$(mktemp -d)
   chmod a+rwx $s2i_volume
-  IMAGE_NAME="${output_image}" create_container s2i-jenkins-test $s2i_volume
+  IMAGE_NAME="${output_image}" run_image s2i-jenkins-test $s2i_volume
   cid=s2i-jenkins-test
   CONTAINER_IP=$(get_container_ip ${cid})
   test_connection ${cid}
-  
+
   if ! docker exec ${cid} ls /var/lib/jenkins/plugins/sample.jpi.pinned; then
     echo "Fail: The sample.jpi.pinned plugin was not copied"
     return 1
@@ -167,12 +197,31 @@ function run_s2i_tests() {
     echo "Fail: The sample-app-test job was not copied"
     return 1
   fi
+
+  set +e
   docker exec ${cid} cat /var/lib/jenkins/config.xml | grep -q "s2i-test-config"
   if [ "$?" != "0" ]; then
     echo "Fail: The config.xml was not copied"
+    docker exec ${cid} cat /var/lib/jenkins/config.xml
+    set -e
     return 1
   fi
-  
+  set -e
+
+  if [[ -n "{VERIFY_INSTALLED:-}" ]]; then
+      if ! docker exec ${cid} ls /var/lib/jenkins/plugins/${VERIFY_INSTALLED}.jpi; then
+          echo "Fail: the ${VERIFY_INSTALLED} plugin was not installed."
+          return 1
+      fi
+  fi
+
+  if [[ -n "{VERIFY_NOT_INSTALLED:-}" ]]; then
+      if docker exec ${cid} ls /var/lib/jenkins/plugins/${VERIFY_NOT_INSTALLED}.jpi; then
+          echo "Fail: the ${VERIFY_NOT_INSTALLED} plugin was installed."
+          return 1
+      fi
+  fi
+
   test_get_job admin password sample-app-test
   test_create_job admin password testJob
   test_get_job admin password testJob
@@ -181,9 +230,32 @@ function run_s2i_tests() {
 # Tests.
 
 # Normal tests
+echo "Normal test: 64 bit"
+VERIFY_NOT_INSTALLED=ansicolor
+CONTAINER_ARGS="-u 10000:0 -e OPENSHIFT_JENKINS_JVM_ARCH=x86_64"
+run_tests jenkins_test
+cleanup
+sleep 5
+echo "Normal test: 32 bit"
+CIDFILE_DIR=$(mktemp --suffix=jenkins_test_cidfiles -d)
+VOLUME=$(mktemp -d)
+chmod a+rwx $VOLUME
+CONTAINER_ARGS="-u 10000:0 -e OPENSHIFT_JENKINS_JVM_ARCH=i386 "
+run_tests jenkins_test
+cleanup
+sleep 5
+echo "Test: install plugins on start"
+CIDFILE_DIR=$(mktemp --suffix=jenkins_test_cidfiles -d)
+VOLUME=$(mktemp -d)
+chmod a+rwx $VOLUME
+VERIFY_INSTALLED=ansicolor
+VERIFY_NOT_INSTALLED=""
+CONTAINER_ARGS="-u 10000:0 -e OPENSHIFT_JENKINS_JVM_ARCH=x86_64 -e INSTALL_PLUGINS=ansicolor:0.4.1"
 run_tests jenkins_test
 
 # S2I tests
 run_s2i_tests
+
+FAILURE=false
 
 echo "SUCCESS!"
